site_name: TPPT Documentation
site_description: Typed Python PowerPoint Tool Documentation
site_author: yassun7010
site_url: https://yassun7010.github.io/tppt/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.tooltips

repo_name: yassun7010/tppt
repo_url: https://github.com/yassun7010/tppt

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
            show_root_heading: true
            show_root_full_path: true
            show_category_heading: true
            show_if_no_docstring: true
            show_signature_annotations: true
            show_bases: true
            show_submodules: true
            group_by_category: true
            heading_level: 2
            members_order: source
          selection:
            docstring_style: google
            filters: ["!^_"]
          paths: [src]
          inventories:
            - src/tppt
            - src/tppt/pptx
            - src/tppt/pptx/dml
            - src/tppt/pptx/shape
            - src/tppt/pptx/text
            - src/tppt/template
            - src/tppt/types
            - src/tppt/exception

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API Reference:
      - tppt: api/tppt.md
      - tppt.pptx: api/tppt_pptx.md
      - tppt.pptx.dml: api/tppt_pptx_dml.md
      - tppt.pptx.shape: api/tppt_pptx_shape.md
      - tppt.pptx.text: api/tppt_pptx_text.md
      - tppt.template: api/tppt_template.md
      - tppt.types: api/tppt_types.md
      - tppt.exception: api/tppt_exception.md
  - Examples: examples.md
  - Contributing: contributing.md
