name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.11.0'
          - '3.12.0'
          - '3.13.0'
      fail-fast: false
    name: Python CI (${{ matrix.python-version }})
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        
    - name: Install dependencies
      run: |
        uv pip install --system .
        uv pip install --system ".[dev]"
        
    - name: Format check
      run: uv run task format-check
      
    - name: Lint
      run: uv run task lint
      
    - name: Type check
      run: uv run task typecheck
      
    - name: Test
      run: uv run task test

  success-python-ci:
    runs-on: ubuntu-latest
    needs: python-ci
    steps:
      - run: echo "All matrix jobs succeeded!"
